import { InstrumentSchema } from "@/types";

export const instrumentSchemas: InstrumentSchema[] = [
  {
    id: "CG0Wheatstone030",
    name: "CG Wheatstone 30",

    buttons: [
      // {
      //   id: "0eerergcg1cs3aku",
      //   x: 16,
      //   y: 16,
      //   shape: "full",
      //   label: "",
      //   note: "A4",
      //   shortcut: "y+space",
      // },
      {
        id: "0egcg1cs3aku",
        x: 16,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "A4",
        shortcut: "y+space",
      },
      {
        id: "jtf4bayk56d",
        x: 2,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "C3",
        shortcut: "s+space",
      },
      {
        id: "zfv52v1vdd",
        x: 0,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "B3",
        shortcut: "z+space",
      },
      {
        id: "x15zrbcrss",
        x: 4,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "D4",
        shortcut: "x+space",
      },
      {
        id: "8gzkud92icl",
        x: 6,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "G3",
        shortcut: "d+space",
      },
      {
        id: "j5xacttuqh",
        x: 12,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "C#4",
        shortcut: "t+space",
      },
      {
        id: "mb12n7xp8dl",
        x: 10,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "C4",
        shortcut: "f+space",
      },
      {
        id: "v8r1myou4vq",
        x: 8,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "G4",
        shortcut: "c+space",
      },
      {
        id: "fovhbvkaosh",
        x: 12,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "B4",
        shortcut: "v+space",
      },
      {
        id: "kkrc0lxge7",
        x: 4,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "E3",
        shortcut: "e+space",
      },
      {
        id: "b64vyaw24mu",
        x: 14,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "E4",
        shortcut: "g+space",
      },
      {
        id: "2qhgip6wc0j",
        x: 18,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "G4",
        shortcut: "h+space",
      },
      {
        id: "5pd62vs1mk",
        x: 16,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "D5",
        shortcut: "b+space",
      },
      {
        id: "hx5fae250na",
        x: 20,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "G#4",
        shortcut: "u+space",
      },
      {
        id: "wyzfbfowt9",
        x: 28,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "C#5",
        shortcut: "8+space",
      },
      {
        id: "e0p89ofw2rr",
        x: 30,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "C5",
        shortcut: "i+space",
      },
      {
        id: "xskczeh90kp",
        x: 32,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "G5",
        shortcut: "k+space",
      },
      {
        id: "hlqljgnujaf",
        x: 32,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "A5",
        shortcut: "9+space",
      },
      {
        id: "8ug6fd4co4b",
        x: 34,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "E5",
        shortcut: "o+space",
      },
      {
        id: "x7ghjzqoc48",
        x: 4,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "F3",
        shortcut: "e",
      },
      {
        id: "mm24zn3bv0m",
        x: 8,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "A3",
        shortcut: "r+space",
      },
      {
        id: "8ean7wfmcdo",
        x: 8,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "Bb3",
        shortcut: "r",
      },
      {
        id: "rix1bl5m9fe",
        x: 2,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "G3",
        shortcut: "s",
      },
      {
        id: "y3mwog1ibz",
        x: 6,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "B3",
        shortcut: "d",
      },
      {
        id: "goi78cf7hj5",
        x: 10,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "D4",
        shortcut: "f",
      },
      {
        id: "fa4zj8tvsf",
        x: 14,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "F4",
        shortcut: "g",
      },
      {
        id: "oxozx3dutjp",
        x: 18,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "A4",
        shortcut: "h",
      },
      {
        id: "fj0r2rt1m79",
        x: 12,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "D#4",
        shortcut: "t",
      },
      {
        id: "iyu0sd7od6e",
        x: 16,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "G4",
        shortcut: "y",
      },
      {
        id: "ziw50ccz0ei",
        x: 20,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "Bb4",
        shortcut: "u",
      },
      {
        id: "c61ciyv92yw",
        x: 0,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "A3",
        shortcut: "z",
      },
      {
        id: "ulem5bbgwu",
        x: 4,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "F#4",
        shortcut: "x",
      },
      {
        id: "9oukyf1k43o",
        x: 8,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "A4",
        shortcut: "c",
      },
      {
        id: "tsd0k9echr9",
        x: 12,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "C5",
        shortcut: "v",
      },
      {
        id: "9kg4uropcxn",
        x: 16,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "E5",
        shortcut: "b",
      },
      {
        id: "ue8z5ok0ld",
        x: 36,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "G#5",
        shortcut: "0+space",
      },
      {
        id: "4c50xp32k1y",
        x: 36,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "B5",
        shortcut: "l+space",
      },
      {
        id: "g6ixmxbulae",
        x: 38,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "G5",
        shortcut: "p+space",
      },
      {
        id: "7e16ahbqjd2",
        x: 40,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "C#6",
        shortcut: "-+space",
      },
      {
        id: "aj43mpvamnf",
        x: 44,
        y: 0,
        shape: "topRightRounded",
        label: "",
        note: "A6",
        shortcut: "=+space",
      },
      {
        id: "bifufpbhap8",
        x: 42,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "C6",
        shortcut: "[+space",
      },
      {
        id: "k0281uafyql",
        x: 46,
        y: 5,
        shape: "topRightRounded",
        label: "",
        note: "E6",
        shortcut: "]+space",
      },
      {
        id: "ob0hx7nglki",
        x: 40,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "D6",
        shortcut: ";+space",
      },
      {
        id: "xxklrsyygmr",
        x: 44,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "G6",
        shortcut: "'+space",
      },
      {
        id: "pkcmon2m96c",
        x: 48,
        y: 10,
        shape: "topRightRounded",
        label: "",
        note: "B6",
        shortcut: "enter+space",
      },
      {
        id: "n86ala2cqr",
        x: 28,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "D#5",
        shortcut: "8",
      },
      {
        id: "s0hrnezrcen",
        x: 32,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "G5",
        shortcut: "9",
      },
      {
        id: "uzun0pybdhh",
        x: 36,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "Bb5",
        shortcut: "0",
      },
      {
        id: "tk0fur56qm8",
        x: 40,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "D#6",
        shortcut: "-",
      },
      {
        id: "5n7m2iovaxm",
        x: 44,
        y: 2,
        shape: "bottomLeftRounded",
        label: "",
        note: "F6",
        shortcut: "=",
      },
      {
        id: "onvcw5fntoo",
        x: 30,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "B4",
        shortcut: "i",
      },
      {
        id: "50wbjvu35xa",
        x: 34,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "D5",
        shortcut: "o",
      },
      {
        id: "atjf5fq7945",
        x: 38,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "F5",
        shortcut: "p",
      },
      {
        id: "2sldc5wtgat",
        x: 42,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "A5",
        shortcut: "[",
      },
      {
        id: "h3ldnt11ltg",
        x: 46,
        y: 7,
        shape: "bottomLeftRounded",
        label: "",
        note: "B5",
        shortcut: "]",
      },
      {
        id: "nc6w3dqeq5",
        x: 32,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "F#5",
        shortcut: "k",
      },
      {
        id: "jqnzv3sncs",
        x: 36,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "A5",
        shortcut: "l",
      },
      {
        id: "8lqsktc1cr6",
        x: 40,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "C6",
        shortcut: ";",
      },
      {
        id: "7d0tw8ukbe",
        x: 44,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "E6",
        shortcut: "'",
      },
      {
        id: "lvgdk5sx32m",
        x: 48,
        y: 12,
        shape: "bottomLeftRounded",
        label: "",
        note: "F#6",
        shortcut: "enter",
      },
    ],
  },
];
